import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import Container from '../../components/Container/Container.jsx'
import Button from '../../components/Button/Button.jsx'
import {
  listMyNotifications,
  markMyNotificationRead,
} from '../../services/candidateService.js'

function formatDateTime(value) {
  if (!value) return '—'
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return '—'
  return date.toLocaleString('en-IN', {
    year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit',
  })
}

function friendlyType(type) {
  switch (type) {
    case 'APPLICATION_STATUS_CHANGED': return 'Application update'
    case 'INTERVIEW_SCHEDULED': return 'Interview scheduled'
    case 'INTERVIEW_UPDATED': return 'Interview updated'
    case 'INTERVIEW_CANCELLED': return 'Interview cancelled'
    default: return type || 'Notification'
  }
}

/**
 * A14 "Notifications" page over GET /candidates/me/notifications (A7.5
 * service, user-scoped by JWT). Read action uses the existing
 * markRead service method; foreign/unknown ids are masked 404s handled as
 * a neutral refresh error. Only real backend data is displayed.
 */
export default function CandidateNotifications() {
  const [page, setPage] = useState(0)
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(false)
  const [reloadKey, setReloadKey] = useState(0)
  const [markingReadId, setMarkingReadId] = useState(null)

  useEffect(() => {
    let active = true
    setLoading(true)
    setError(false)
    listMyNotifications({ page, size: 10 })
      .then(result => {
        if (active) setData(result)
      })
      .catch(() => {
        if (active) setError(true)
      })
      .finally(() => {
        if (active) setLoading(false)
      })
    return () => {
      active = false
    }
  }, [page, reloadKey])

  const items = data ? data.items : []

  function handleMarkRead(notification) {
    if (markingReadId !== null) return
    setMarkingReadId(notification.id)
    markMyNotificationRead(notification.id)
      .then(updated => {
        setData(current => current && {
          ...current,
          items: current.items.map(item =>
            item.id === notification.id ? { ...item, ...updated } : item),
        })
      })
      .catch(() => setError(true))
      .finally(() => setMarkingReadId(null))
  }

  return (
    <Container>
      <div className="candidate-portal__panel">
        <h1 className="candidate-portal__title">Notifications</h1>
        <p className="candidate-portal__muted">
          Updates about your applications and interviews. Notifications are
          generated by the foundation's hiring team activity — you cannot
          reply from here.
        </p>

        {loading && (
          <div aria-hidden="true">
            <div className="candidate-portal__skeleton candidate-portal__skeleton--title" />
            <div className="candidate-portal__skeleton candidate-portal__skeleton--line" />
            <div className="candidate-portal__skeleton candidate-portal__skeleton--short" />
          </div>
        )}

        {!loading && error && (
          <>
            <p className="candidate-portal__error" role="alert">
              We could not load your notifications right now. Please try again.
            </p>
            <Button variant="primary" size="medium" onClick={() => setReloadKey(key => key + 1)}>
              Try again
            </Button>
          </>
        )}

        {!loading && !error && data && items.length === 0 && (
          <p className="candidate-portal__muted">
            <strong>No notifications yet.</strong>{' '}
            Updates about your applications and interviews will appear here.
          </p>
        )}

        {!loading && !error && data && items.length > 0 && (
          <>
            <ul className="candidate-portal__list">
              {items.map(item => (
                <li
                  key={item.id}
                  className={`candidate-portal__list-item${item.readAt ? '' : ' candidate-portal__list-item--unread'}`}
                >
                  <div className="candidate-portal__row">
                    <div>
                      <strong>{item.title || friendlyType(item.type)}</strong>
                      <div className="candidate-portal__muted">{item.body}</div>
                      <div className="candidate-portal__muted candidate-portal__muted--small">
                        {formatDateTime(item.createdAt)}
                      </div>
                    </div>
                    {!item.readAt && (
                      <Button
                        variant="outline"
                        size="small"
                        disabled={markingReadId !== null}
                        onClick={() => handleMarkRead(item)}
                      >
                        {markingReadId === item.id ? 'Marking…' : 'Mark read'}
                      </Button>
                    )}
                  </div>
                </li>
              ))}
            </ul>

            <div className="candidate-portal__row" style={{ marginTop: 'var(--spacing-4)' }}>
              <Button
                variant="outline"
                size="small"
                disabled={page === 0 || loading}
                onClick={() => setPage(current => Math.max(0, current - 1))}
              >
                Previous
              </Button>
              <span className="candidate-portal__muted">
                Page {data.page + 1} of {Math.max(1, data.totalPages)}
              </span>
              <Button
                variant="outline"
                size="small"
                disabled={page + 1 >= data.totalPages || loading}
                onClick={() => setPage(current => current + 1)}
              >
                Next
              </Button>
            </div>
          </>
        )}
      </div>
    </Container>
  )
}
